<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GpxView.Core\GpxView.Core.csproj" />
    <ProjectReference Include="..\GpxView.Geo\GpxView.Geo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Garmin.FIT.Sdk" Version="21.205.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
