using System.Globalization;

namespace GpxView.App;

internal sealed class LocalizationCatalog
{
    private sealed record Translation(string Zh, string En);

    private static readonly IReadOnlyDictionary<string, Translation> Entries =
        new Dictionary<string, Translation>(StringComparer.Ordinal)
        {
            ["App.Ready"] = new("就绪", "Ready"),
            ["Toolbar.Open"] = new("打开", "Open"),
            ["Toolbar.OpenTooltip"] = new("打开轨迹文件", "Open track files"),
            ["Toolbar.Recent"] = new("最近", "Recent"),
            ["Toolbar.RecentTooltip"] = new("显示最近打开的轨迹", "Show recently opened tracks"),
            ["Toolbar.BaseMap"] = new("选择底图", "Choose base map"),
            ["Toolbar.Coordinates"] = new("选择源坐标系", "Choose source coordinate system"),
            ["Toolbar.RoadNetwork"] = new("路网", "Trails"),
            ["Toolbar.Settings"] = new("设置", "Settings"),
            ["Map.Modern"] = new("现代", "Modern"),
            ["Map.ModernTooltip"] = new("OpenFreeMap 现代矢量地图", "OpenFreeMap modern vector map"),
            ["Map.Outdoor"] = new("户外", "Outdoor"),
            ["Map.OutdoorTooltip"] = new("户外矢量地图：步道、等高线与地形阴影", "Outdoor vector map with trails, contours, and hillshade"),
            ["Map.Classic"] = new("经典", "Classic"),
            ["Map.ClassicTooltip"] = new("OpenStreetMap 经典地图", "Classic OpenStreetMap"),
            ["Map.Street"] = new("街道", "Street"),
            ["Map.StreetTooltip"] = new("天地图街道", "Tianditu street map"),
            ["Map.Imagery"] = new("影像", "Imagery"),
            ["Map.ImageryTooltip"] = new("天地图影像", "Tianditu imagery"),
            ["Map.Terrain"] = new("地形", "Terrain"),
            ["Map.TerrainTooltip"] = new("天地图地形", "Tianditu terrain"),
            ["Map.TiandituMissing"] = new("请配置 MapServices.local.json", "Configure MapServices.local.json to enable Tianditu"),
            ["Map.Satellite"] = new("卫星", "Satellite"),
            ["Map.SatelliteTooltip"] = new("Esri 卫星影像", "Esri satellite imagery"),
            ["Map.Topo"] = new("等高线", "Topo"),
            ["Map.TopoTooltip"] = new("OpenTopoMap 地形与等高线", "OpenTopoMap terrain and contours"),
            ["Map.Humanitarian"] = new("人道主义", "Humanitarian"),
            ["Map.HumanitarianTooltip"] = new("OpenStreetMap Humanitarian 风格", "OpenStreetMap Humanitarian style"),
            ["Coordinates.Wgs84"] = new("WGS84（标准）", "WGS84 (standard)"),
            ["Coordinates.Gcj02"] = new("GCJ-02", "GCJ-02"),
            ["Coordinates.Bd09"] = new("BD-09", "BD-09"),
            ["Terrain.Enable"] = new("切换到三维地形", "Switch to 3D terrain"),
            ["Terrain.Disable"] = new("切换到二维地图", "Switch to 2D map"),
            ["Theme.System"] = new("跟随系统", "System"),
            ["Theme.Light"] = new("浅色", "Light"),
            ["Theme.Dark"] = new("深色", "Dark"),
            ["Theme.Tooltip"] = new("主题：{0}（点击切换）", "Theme: {0} (click to switch)"),
            ["Status.Opening"] = new("正在打开 {0}", "Opening {0}"),
            ["Status.OpeningBatch"] = new("正在打开 {0}/{1} · {2}", "Opening {0}/{1} · {2}"),
            ["Status.Reloading"] = new("正在重新解析 {0}/{1} · {2}", "Reloading {0}/{1} · {2}"),
            ["Status.MapUnavailable"] = new("地图图层暂时无法加载", "The map layer is temporarily unavailable"),
            ["Status.WebViewFailed"] = new("WebView2 初始化失败，地图暂不可用。", "WebView2 failed to initialize; the map is unavailable."),
            ["Status.DefaultAppsFailed"] = new("无法打开 Windows 默认应用设置。", "Windows default-app settings could not be opened."),
            ["Status.FileAssociationUpdated"] = new("已将 {0} 设置为用 GpxView 打开。", "{0} now opens with GpxView."),
            ["Status.FileAssociationNeedsConfirmation"] = new("GpxView 已注册为 {0} 的打开方式；Windows 仍要求在默认应用里确认。", "GpxView is registered for {0}; Windows still requires confirmation in default-app settings."),
            ["Status.FileAssociationFailed"] = new("无法更新 {0} 文件关联。", "The {0} file association could not be updated."),
            ["Status.RoadFolderFailed"] = new("无法打开本地路网目录。", "The local trail folder could not be opened."),
            ["Status.RoadNetworkCacheCleared"] = new("已清理远程路网缓存。", "The remote trail cache was cleared."),
            ["Status.RoadNetworkCacheClearFailed"] = new("无法清理远程路网缓存。", "The remote trail cache could not be cleared."),
            ["Status.ProjectHomeFailed"] = new("无法打开项目主页。", "The project home page could not be opened."),
            ["Dialog.OpenTitle"] = new("打开轨迹文件", "Open track files"),
            ["Dialog.TrackFilter"] = new("轨迹文件 (*.gpx;*.kml;*.kmz;*.fit)|*.gpx;*.kml;*.kmz;*.fit|所有文件 (*.*)|*.*", "Track files (*.gpx;*.kml;*.kmz;*.fit)|*.gpx;*.kml;*.kmz;*.fit|All files (*.*)|*.*"),
            ["Dialog.PartialOpenTitle"] = new("部分轨迹无法打开", "Some tracks could not be opened"),
            ["Dialog.PartialReloadTitle"] = new("部分轨迹无法重新解析", "Some tracks could not be reloaded"),
            ["Dialog.FileError"] = new("{0}：{1}", "{0}: {1}"),
            ["Dialog.UnexpectedReadError"] = new("{0}：读取时发生未预期错误（{1}）", "{0}: unexpected error while reading ({1})"),
            ["Dialog.UnexpectedReloadError"] = new("{0}：重新解析时发生未预期错误（{1}）", "{0}: unexpected error while reloading ({1})"),
            ["Dialog.WebViewTitle"] = new("地图初始化失败", "Map initialization failed"),
            ["Dialog.WebViewMessage"] = new("无法初始化地图组件：\n{0}\n\n请安装或修复 Microsoft Edge WebView2 Runtime。", "The map component could not be initialized:\n{0}\n\nInstall or repair Microsoft Edge WebView2 Runtime."),
            ["Dialog.MissingFileTitle"] = new("找不到文件", "File not found"),
            ["Dialog.MissingFileMessage"] = new("文件已不存在，已从最近记录中移除：\n{0}", "The file no longer exists and was removed from Recent:\n{0}"),
            ["Summary.FormatLine"] = new("{0} · {1} 分段 · {2:N0} 轨迹点", "{0} · {1} segments · {2:N0} track points"),
            ["Summary.StatusPoints"] = new("{0:N0} 点", "{0:N0} points"),
            ["Summary.StatusWaypoints"] = new("{0:N0} 标注", "{0:N0} waypoints"),
            ["Place.Disabled"] = new("地点识别已关闭", "Place recognition is off"),
            ["Place.Unavailable"] = new("地点暂不可用", "Place unavailable"),
            ["Place.Recognizing"] = new("正在识别地点…", "Recognizing place…"),
            ["RoadNetwork.HideOne"] = new("隐藏{0}路网", "Hide {0}"),
            ["RoadNetwork.ShowOne"] = new("显示{0}路网", "Show {0}"),
            ["RoadNetwork.Count"] = new("{0} 个路网归档", "{0} trail archives"),
            ["RoadNetwork.Beijing"] = new("北京历史轨迹密度（2017）", "Beijing historical trail density (2017)"),
            ["RoadNetwork.Hebei"] = new("河北历史轨迹密度（2017）", "Hebei historical trail density (2017)"),
            ["RoadNetwork.Mentougou"] = new("门头沟历史轨迹密度（实验）", "Mentougou historical trail density (experiment)"),
            ["Settings.Title"] = new("设置", "Settings"),
            ["Settings.Close"] = new("关闭设置", "Close settings"),
            ["Settings.General"] = new("通用", "General"),
            ["Settings.Language"] = new("界面语言", "Display language"),
            ["Settings.LanguageSystem"] = new("跟随系统", "Use system language"),
            ["Settings.LanguageChinese"] = new("简体中文", "Simplified Chinese"),
            ["Settings.LanguageEnglish"] = new("English", "English"),
            ["Settings.Geocoding"] = new("地点识别", "Place recognition"),
            ["Settings.GeocodingDescription"] = new("把轨迹文件中的一个低精度代表坐标发送给 OpenStreetMap Nominatim，以显示地区名称；不读取设备当前位置。默认关闭。", "Sends one low-precision representative coordinate from the track file to OpenStreetMap Nominatim to show an area name. It does not read the device's current location. Off by default."),
            ["Settings.Files"] = new("文件", "Files"),
            ["Settings.FileAssociations"] = new("文件关联", "File associations"),
            ["Settings.FileAssociationsDescription"] = new("在这里为 GPX、KML、KMZ 和 FIT 设置默认打开方式；若 Windows 已锁定其他默认程序，会要求系统确认。", "Set GPX, KML, KMZ, and FIT defaults here. If Windows has locked another default app, system confirmation may still be required."),
            ["Settings.OpenDefaultApps"] = new("打开 Windows 默认应用", "Open Windows default apps"),
            ["Settings.Associated"] = new("已关联", "Associated"),
            ["Settings.NotAssociated"] = new("未关联", "Not associated"),
            ["Settings.AssociateWithGpxView"] = new("设为 GpxView", "Use GpxView"),
            ["Settings.ConfirmInWindows"] = new("在 Windows 中选择", "Choose in Windows"),
            ["Settings.RoadNetworks"] = new("路网", "Trails"),
            ["Settings.RoadNetworkDescription"] = new("GpxView 扫描此目录顶层的 PMTiles 文件；当前归档范围应互不重叠。", "GpxView scans PMTiles files in the top level of this folder. Archive bounds should not overlap."),
            ["Settings.OpenRoadFolder"] = new("打开路网目录", "Open trail folder"),
            ["Settings.RefreshRoadNetworks"] = new("刷新", "Refresh"),
            ["Settings.NoRoadNetworks"] = new("尚未发现 PMTiles 路网文件。", "No PMTiles trail archives found."),
            ["Settings.ZoomRange"] = new("缩放级别 {0}–{1}", "Zoom levels {0}–{1}"),
            ["Settings.RoadNetworkCache"] = new("远程路网缓存", "Remote trail cache"),
            ["Settings.RoadNetworkCacheDescription"] = new("已缓存 {0}，{1} 个数据块。", "Cached {0} in {1} blocks."),
            ["Settings.RoadNetworkCacheEmpty"] = new("尚未缓存远程路网瓦片。", "No remote trail tiles are cached yet."),
            ["Settings.ClearRoadNetworkCache"] = new("清理缓存", "Clear cache"),
            ["Settings.ClearingRoadNetworkCache"] = new("正在清理…", "Clearing…"),
            ["Settings.OnlineRoadNetworks"] = new("在线路网", "Online trail service"),
            ["Settings.OnlineRoadNetworkDescription"] = new("使用服务地址和一次性激活码连接私有路网。设备令牌保存在 Windows 凭据管理器中，不会交给地图网页。", "Connect to a private trail service with its address and a one-time enrollment code. The device token stays in Windows Credential Locker and is never exposed to the map page."),
            ["Settings.ServiceEndpoint"] = new("服务地址", "Service address"),
            ["Settings.EnrollmentCode"] = new("一次性激活码", "One-time enrollment code"),
            ["Settings.Connect"] = new("连接", "Connect"),
            ["Settings.Disconnect"] = new("断开", "Disconnect"),
            ["Settings.PrivateService"] = new("私有路网服务", "Private trail service"),
            ["Settings.OnlineDisconnected"] = new("尚未连接私有路网服务。", "Not connected to a private trail service."),
            ["Settings.OnlineConnecting"] = new("正在连接并读取路网目录…", "Connecting and loading the trail catalog…"),
            ["Settings.OnlineConnected"] = new("已连接：{0}", "Connected: {0}"),
            ["Settings.OnlineInvalidEndpoint"] = new("服务地址无效；公网服务必须使用 HTTPS。", "The service address is invalid; public services must use HTTPS."),
            ["Settings.OnlineInvalidCode"] = new("激活码无效、已使用或已过期。", "The enrollment code is invalid, already used, or expired."),
            ["Settings.OnlineAuthenticationFailed"] = new("设备凭据已失效，请断开后使用新的激活码连接。", "The device credential is no longer valid. Disconnect, then connect with a new enrollment code."),
            ["Settings.OnlineCredentialError"] = new("无法访问 Windows 凭据管理器。", "Windows Credential Locker is unavailable."),
            ["Settings.OnlineError"] = new("暂时无法连接路网服务，请稍后重试。", "The trail service is temporarily unavailable. Try again later."),
            ["Settings.About"] = new("关于", "About"),
            ["Settings.Version"] = new("版本", "Version"),
            ["Settings.Channel"] = new("发布渠道", "Distribution channel"),
            ["Settings.ChannelGitHub"] = new("GitHub 版", "GitHub build"),
            ["Settings.ChannelStore"] = new("Microsoft Store 版", "Microsoft Store build"),
            ["Settings.ProjectHome"] = new("项目主页", "Project home"),
            ["Settings.Privacy"] = new("隐私政策", "Privacy policy"),
            ["Settings.ThirdParty"] = new("第三方许可与服务", "Third-party notices"),
            ["Settings.Compliance"] = new("合规与许可", "Legal and compliance"),
            ["Consent.Title"] = new("是否开启地点识别？", "Enable place recognition?"),
            ["Consent.Description"] = new("开启后，GpxView 会把轨迹文件中的一个低精度代表坐标发送给 OpenStreetMap Nominatim 来识别地区名称。它不会读取设备当前位置，也不会上传轨迹文件或完整路线。你可以随时在设置中关闭。", "When enabled, GpxView sends one low-precision representative coordinate from the track file to OpenStreetMap Nominatim to identify an area name. It does not read the device's current location or upload the track file or full route. You can turn this off in Settings at any time."),
            ["Consent.Allow"] = new("允许地点识别", "Allow place recognition"),
            ["Consent.Decline"] = new("暂不开启", "Not now"),
            ["Consent.ReadPrivacy"] = new("阅读隐私政策", "Read privacy policy"),
            ["Web.RecentTitle"] = new("最近轨迹", "Recent tracks"),
            ["Web.Waypoint"] = new("标注点", "Waypoint"),
            ["Web.WaypointElevation"] = new("海拔 {0} m", "Elevation {0} m"),
            ["Web.DistanceFromStart"] = new("距起点 {0}", "Distance from start {0}"),
            ["Web.OpenFile"] = new("打开文件", "Open files"),
            ["Web.Close"] = new("关闭", "Close"),
            ["Web.WelcomeTitle"] = new("GpxView", "GpxView"),
            ["Web.WelcomeDescription"] = new("在本机查看轨迹、海拔、标注点和授权路网。轨迹文件只在本机解析，不会上传。", "View tracks, elevation, waypoints, and licensed road networks locally. Track files are parsed on this device and are never uploaded."),
            ["Web.WelcomeOpen"] = new("打开 GPX / KML / KMZ / FIT", "Open GPX / KML / KMZ / FIT"),
            ["Web.WelcomeHint"] = new("也可以把多个轨迹文件直接拖到这里，或关闭此提示直接浏览地图", "You can also drop multiple track files here, or close this message to browse the map."),
            ["Web.RecentFooter"] = new("地名由 Nominatim 提供，数据 © OpenStreetMap contributors", "Places by Nominatim; data © OpenStreetMap contributors"),
            ["Web.TrackSummary"] = new("轨迹摘要", "Track summary"),
            ["Web.NoFile"] = new("尚未打开文件", "No file is open"),
            ["Web.Location"] = new("地点", "Place"),
            ["Web.Distance"] = new("距离", "Distance"),
            ["Web.Duration"] = new("总用时 / 移动时间", "Elapsed / moving time"),
            ["Web.ElevationGainLoss"] = new("累计爬升 / 下降", "Elevation gain / loss"),
            ["Web.SpeedAverageMax"] = new("平均 / 最大速度", "Average / maximum speed"),
            ["Web.HeartRateAverageMax"] = new("平均 / 最大心率", "Average / maximum heart rate"),
            ["Web.CadencePower"] = new("踏频 / 功率", "Cadence / power"),
            ["Web.HideDetails"] = new("隐藏详细信息（Tab）", "Hide details (Tab)"),
            ["Web.ShowDetails"] = new("显示详细信息（Tab）", "Show details (Tab)"),
            ["Web.TrackChart"] = new("轨迹曲线", "Track chart"),
            ["Web.ElevationChart"] = new("海拔曲线", "Elevation chart"),
            ["Web.ActivityChart"] = new("运动曲线", "Activity chart"),
            ["Web.SeriesHint"] = new("选择要叠加的曲线；悬停查看真实值", "Choose overlays; hover to inspect values"),
            ["Web.Elevation"] = new("海拔", "Elevation"),
            ["Web.Slope"] = new("坡度", "Slope"),
            ["Web.HeartRate"] = new("心率", "Heart rate"),
            ["Web.Speed"] = new("速度", "Speed"),
            ["Web.Power"] = new("功率", "Power"),
            ["Web.Track"] = new("轨迹", "Track"),
            ["Web.TrackColor"] = new("轨迹颜色", "Track color"),
            ["Web.TrackColorRange"] = new("轨迹颜色范围", "Track color range"),
            ["Web.UniformColor"] = new("统一颜色", "Uniform color"),
            ["Web.ColorByElevation"] = new("按海拔", "By elevation"),
            ["Web.ColorBySlope"] = new("按坡度", "By slope"),
            ["Web.ColorBySpeed"] = new("按速度", "By speed"),
            ["Web.ColorByHeartRate"] = new("按心率", "By heart rate"),
            ["Web.ColorByPower"] = new("按功率", "By power"),
            ["Web.NoData"] = new("暂无数据", "No data"),
            ["Web.Play"] = new("播放轨迹", "Play track"),
            ["Web.Pause"] = new("暂停轨迹回放", "Pause track playback"),
            ["Web.PlaybackProgress"] = new("轨迹回放进度", "Track playback progress"),
            ["Web.PlaybackDuration"] = new("预计播放时长上限", "Maximum playback duration"),
            ["Web.WithinMinutes"] = new("{0}分钟内", "Within {0} minutes"),
            ["Web.WithinSeconds"] = new("{0}秒内", "Within {0} seconds"),
            ["Web.Follow"] = new("跟随", "Follow"),
            ["Web.FollowTooltip"] = new("让地图跟随回放位置", "Keep the map centered on playback"),
            ["Web.OpenTracks"] = new("已打开的轨迹", "Open tracks"),
            ["Web.HideOnMap"] = new("在地图上隐藏", "Hide on map"),
            ["Web.ShowOnMap"] = new("在地图上显示", "Show on map"),
            ["Web.HideTrack"] = new("隐藏 {0}", "Hide {0}"),
            ["Web.ShowTrack"] = new("显示 {0}", "Show {0}"),
            ["Web.ViewTrack"] = new("查看 {0} 的摘要与海拔图", "View summary and elevation chart for {0}"),
            ["Web.CloseTrack"] = new("关闭 {0}", "Close {0}"),
            ["Web.UntitledTrack"] = new("未命名轨迹", "Untitled track"),
            ["Web.PlaceUnknown"] = new("地点尚未识别", "Place not recognized"),
            ["Web.NoElevation"] = new("无海拔数据", "No elevation data"),
            ["Web.RecentEmptyTitle"] = new("还没有最近轨迹", "No recent tracks"),
            ["Web.RecentEmptyDescription"] = new("打开轨迹后会在这里留下快速入口。", "Tracks you open will appear here for quick access."),
            ["Web.GroundElevation"] = new("地面海拔 {0} m", "Ground elevation {0} m"),
            ["Web.OutdoorLoadFailed"] = new("等高线暂时无法加载，已保留户外矢量底图", "Contours are unavailable; the outdoor vector map remains active"),
            ["Web.TerrainLoadFailed"] = new("三维地形数据暂时无法加载，已切回二维地图", "3D terrain is unavailable; switched back to 2D"),
            ["Web.North"] = new("北", "N"),
            ["Web.NorthEast"] = new("东北", "NE"),
            ["Web.East"] = new("东", "E"),
            ["Web.SouthEast"] = new("东南", "SE"),
            ["Web.South"] = new("南", "S"),
            ["Web.SouthWest"] = new("西南", "SW"),
            ["Web.West"] = new("西", "W"),
            ["Web.NorthWest"] = new("西北", "NW"),
            ["Web.CompassNorth"] = new("当前朝向：正北；点击回到正北", "Facing north; click to reset"),
            ["Web.CompassBearing"] = new("当前朝向：{0} {1}°；点击回到正北", "Facing {0} {1}°; click to reset"),
            ["Web.RoadAttribution"] = new("本地历史轨迹密度", "Local historical trail density"),
            ["Legal.DocumentTitle"] = new("文档", "Document"),
            ["Legal.LoadFailed"] = new("无法读取此文档。", "This document could not be loaded.")
        };

    private LocalizationCatalog(string preference)
    {
        Preference = preference is "zh-CN" or "en-US" ? preference : "system";
        var requested = Preference == "system" ? CultureInfo.CurrentUICulture.Name : Preference;
        Locale = requested.StartsWith("zh", StringComparison.OrdinalIgnoreCase) ? "zh-CN" : "en-US";
        Culture = CultureInfo.GetCultureInfo(Locale);
    }

    public string Preference { get; }
    public string Locale { get; }
    public CultureInfo Culture { get; }

    public static LocalizationCatalog Create(string preference) => new(preference);

    public string Get(string key) => Entries.TryGetValue(key, out var value)
        ? Locale == "zh-CN" ? value.Zh : value.En
        : key;

    public string Format(string key, params object?[] values) =>
        string.Format(Culture, Get(key), values);

    public Dictionary<string, string> Export() => Entries.ToDictionary(
        entry => entry.Key,
        entry => Locale == "zh-CN" ? entry.Value.Zh : entry.Value.En,
        StringComparer.Ordinal);
}
